### ISSUE TITLE
Cannot delete topic?

### ISSUE THREAD

**Issue by Moult** [podestplatz/bcf#2]
Ping @podestplatz 

I'm not entirely sure how to delete a topic:

```
>>> bcfplugin.getTopics()
[('Maximum Content', <bcfplugin.rdwr.topic.Topic object at 0x7f14a65d8fd0>), ('Referenced topic', <bcfplugin.rdwr.topic.Topic object at 0x7f14a65a4e10>)]

>>> bcfplugin.deleteObject(bcfplugin.getTopics()[0][1])
<OperationResults.SUCCESS: 1>

>>> bcfplugin.getTopics()
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/dion/.config/blender/2.82/scripts/addons/blenderbim/libs/site/packages/bcfplugin/programmaticInterface.py", line 381, in getTopics
    topics.append((topic.title, topic))
AttributeError: 'NoneType' object has no attribute 'title'
```

**Comment by podestplatz** [comment]
Hey @Moult 

I will look into it today. One thought occurred to me while skimming through the test cases for the programmatic interface, that maybe I didn't intend topics to be deleted, because I don't have written any test case for it.
But I will check.

**Comment by podestplatz** [comment]
The commit https://github.com/podestplatz/bcf/commit/fcf5f24e81da4f0785f183974e012f2e3478c2af is a quick fix for the error you are getting, although it might not solve the underlying issue. To test it I have added the `DeleteObjectTests.test_deleteTopic()` test in `interface_test.py`, that reproduces the steps you have shown. When you call `bcfplugin.deleteObject()` on a topic, the parent object (of type `Markup` is fetched, and its member `topic` is set to `None`, but the rest of the markup is preserved, like the list of comments. In `programmaticInterface.py:getTopics()` I now simply skip markup nodes whose `topic` member is `None`.

However, as I remember the bcf specification, and I think you are now much more of an expert on this than I am, a `markup.bcf` file only contains one topic. This would imply, IMO, that when we delete a topic, the containing instance of type `Markup`, with its associated file and directory, shall also be deleted, which is not done and probably will require a bit more effort, especially in the `rdwr.writer` module.
