### ISSUE TITLE
Error when opening bcf project

### ISSUE THREAD

**Issue by TZwielehner** [podestplatz/bcf#5]
I tried to open a sample file with the openProject command (I renamed this [one ](bcf-examples/Issues_BIMcollab_Example_pr_2018-01-31_17.08.bcf) to sample.bcf) and got the following error. Any idea what the problem might be?
```
>>> p = bcf.openProject("sample.bcf")
[INFO]programmaticInterface.openProject(): Opening sample.bcf
[DEBUG]reader.readBcfFile(): Reading file sample.bcf and instantiating the data model
[DEBUG]reader.extractFileToTmp(): Extracting sample.bcf to C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\sample.bcf
[DEBUG]reader.validateFile(): Validating file C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\sample.bcf\bcf.version against C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\version.xsd
[DEBUG]reader.getVersion(): Retrieving version from the BCF project
[DEBUG]reader.getVersion(): Version of the BCF project is 2.1
[DEBUG]reader.validateFile(): Validating file C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\sample.bcf\project.bcfp against C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\project.xsd
[DEBUG]reader.buildProject(): Building new project object.
[DEBUG]reader.buildProject(): New project object created 'Project(
id='14b6afe9-866c-494a-97d6-ddb44971814e',
name='BIMcollab Example project',
extSchemaSrc='None',
topicList='[]')'
[DEBUG]reader.readBcfFile(): Topic 0a36e3d6-97e9-47d6-ab4f-227990429f52 gets builded next
[DEBUG]reader.readBcfFile(): reading topic C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\sample.bcf\0a36e3d6-97e9-47d6-ab4f-227990429f52
[DEBUG]reader.validateFile(): Validating file C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\sample.bcf\0a36e3d6-97e9-47d6-ab4f-227990429f52\markup.bcf against C:\Users\abc\AppData\Local\Temp\bcfplugin_ytdp34ut\markup.xsd
[ERROR]reader.readBcfFile(): markup.bcf of topic 0a36e3d6-97e9-47d6-ab4f-227990429f52 does not comply with the standard of versions ['2.0', '2.1']. Some parts won't be available.
[DEBUG]reader.buildMarkup(): Building new Markup object
[DEBUG]reader.buildComment(): Building new comment object
[DEBUG]reader.buildComment(): New comment object created Do you mean this one? -- bgreen@bim.col, 2014-10-16 14:35:29 modified on 2014-10-16 14:35:29
[DEBUG]reader.buildTopic(): Creating new Topic object
[DEBUG]reader.buildTopic(): New Topic object created
[DEBUG]reader.buildViewpointReference(): Building new ViewpointReference object
[DEBUG]reader.buildViewpointReference(): New ViewpointReference object created
[DEBUG]reader.buildSnapshotList(): Building SnapshotList
[DEBUG]reader.buildSnapshotList(): New SnapshotList created
[DEBUG]reader.buildMarkup(): New Markup object created
[DEBUG]reader.buildViewpoint(): Building new Viewpoint object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\Lib\site-packages\bcfplugin\programmaticInterface.py", line 178, in openProject
    project = reader.readBcfFile(bcfFile)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\bcfplugin\rdwr\reader.py", line 798, in readBcfFile
    vp = buildViewpoint(vpPath, visinfoSchemaPath)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\bcfplugin\rdwr\reader.py", line 637, in buildViewpoint
    vpSchema = modifyVisinfoSchema(vpSchema)
  File "C:\Users\abc\AppData\Local\Programs\Python\Python38\lib\site-packages\bcfplugin\rdwr\reader.py", line 68, in modifyVisinfoSchema
    schema.__dict__["types"].__dict__["target_dict"]["FieldOfView"].__dict__["validators"][1].value = 360
AttributeError: 'NamespaceView' object has no attribute '__dict__'


```

**Comment by Moult** [comment]
Sorry to be "that guy" but have you considered using https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/bcf instead? It is designed to supersede this library and is currently used in the BlenderBIM Add-on, and starting to be used by some folks from FreeCAD.

Some history: https://community.osarch.org/discussion/90/ and how it evolved into the IfcOpenShell rewrite https://community.osarch.org/discussion/372/

**Comment by TZwielehner** [comment]
Nope, haven't yet. I'll do that.
How about the bcf support for bimtester? I just had a look into that library and I think it is greatly undervalued (I have to deal with Solibri on a regular basis).
